version: "2"
services:
    proxy:
        image: httpd
        depends_on:
          - web
    web:
        image: node:8.12.0-jessie
        ports: 
          - "8080:80"
        depends_on:
        - redis
    redis:
        image: redis